# Porta do Servidor MCP (Evita conflito com o Agente na 8080) 
quarkus.http.port=8081

# Metadados do Servidor 
quarkus.mcp.server.server-info.name=Cliente-Tools-Service
quarkus.mcp.server.server-info.version=1.0.0

# Permite ver o JSON-RPC de cada transação 
quarkus.mcp.server.traffic-logging.enabled=true
quarkus.mcp.server.traffic-logging.text-limit=2000

# Datasource MySQL
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=123456
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/mercearia2

# Hibernate ORM
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# Opcional: mostra os parâmetros SQL no log
quarkus.hibernate-orm.log.bind-parameters=true

quarkus.mailer.from=mercearia.api@gmail.com
quarkus.mailer.host=smtp.gmail.com
quarkus.mailer.port=587
quarkus.mailer.username=mercearia.api@gmail.com
quarkus.mailer.password=vocfjirdnteauqjr

quarkus.mailer.start-tls=REQUIRED
quarkus.mailer.login=REQUIRED
quarkus.mailer.mock=false



quarkus.devservices.enabled=false