# URL de conexão com o PostgreSQL
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/rag_db

# Usuário do PostgreSQL
quarkus.datasource.username=postgres

# Senha do PostgreSQL
quarkus.datasource.password=123456

# Chave utilizada para acessar a API da OpenAI
quarkus.langchain4j.openai.api-key=

# Modelo da OpenAI responsável por gerar os embeddings
quarkus.langchain4j.openai.embedding-model.model-name=text-embedding-3-small

# Dimensão dos vetores armazenados no PGVector
quarkus.langchain4j.pgvector.dimension=1536

# Nome da tabela onde os chunks e embeddings serão armazenados
quarkus.langchain4j.pgvector.table=knowledge_embeddings

# Cria a tabela de embeddings caso ela ainda não exista
quarkus.langchain4j.pgvector.create-table=true

# Mantém os embeddings existentes quando a aplicação reiniciar
quarkus.langchain4j.pgvector.drop-table-first=false

# Registra a extensão "vector" no PostgreSQL caso necessário
quarkus.langchain4j.pgvector.register-vector-pg-extension=true