quarkus.application.name=inventory-service

# Porta HTTP do inventory-service
quarkus.http.port=8082
quarkus.devservices.enabled=false
# MySQL
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=123456
quarkus.datasource.jdbc.url=jdbc:mysql://host.docker.internal:3306/estoque

# Hibernate ORM
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.format-sql=true

# CORS
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS,HEAD,TRACE,CONNECT
quarkus.http.cors.headers=*

# MCP Server
quarkus.mcp.server.server-info.name=inventory-service
quarkus.mcp.server.server-info.title=Inventory Service MCP
quarkus.mcp.server.server-info.version=1.0.0
quarkus.mcp.server.server-info.description=Servidor MCP para consulta, cadastro e atualização de produtos do estoque.

reprocess.history.exchange=customer.reprocess.history.exchange
reprocess.history.routing-key=customer.reprocess.history.routing-key

# Publisher: reprocess history
mp.messaging.outgoing.reprocess-history-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.reprocess-history-out.exchange.name=${reprocess.history.exchange}
mp.messaging.outgoing.reprocess-history-out.routing-key=${reprocess.history.routing-key}